vpc_name    = "test-vpc"
subnet_name = "testsubnet1"
bucket_name = "terraform_learning_test_bucket_7869"
terraform_service_account = "terraform-gcp@terraform-learning-412915.iam.gserviceaccount.com"
project_id = "terraform-learning-412915"
